"""Regenerate index/cards.json and index/INDEX.md from all cards."""
from __future__ import annotations

import json
from datetime import date

from kblib import (DOMAINS, PENDING_DIR, ROOT, first_section_paragraphs,
                   iter_cards, utf8_stdout)


def main() -> None:
    utf8_stdout()
    cards = [c for c in iter_cards() if not c.parse_error]
    index = []
    for card in cards:
        meta = card.meta
        paras = first_section_paragraphs(card.body)
        index.append({
            "slug": card.slug,
            "path": card.rel_path,
            "folder": card.folder,
            "title": meta.get("title", card.slug),
            "type": meta.get("type", ""),
            "domain": meta.get("domain", ""),
            "source_type": meta.get("source_type", ""),
            "status": meta.get("status", ""),
            "tags": meta.get("tags") or [],
            "authors": meta.get("authors") or [],
            "year": meta.get("year"),
            "citation_key": meta.get("citation_key", ""),
            "related": meta.get("related") or [],
            "drive": meta.get("drive") or [],
            "created": str(meta.get("created", "")),
            "summary": paras[0] if paras else "",
        })
    index.sort(key=lambda c: (c["domain"], c["type"], c["slug"]))

    out_dir = ROOT / "index"
    out_dir.mkdir(exist_ok=True)
    (out_dir / "cards.json").write_text(
        json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    lines = [
        "# Index",
        "",
        f"Auto-generated by `scripts/update_index.py` on {date.today()} — do not edit by hand.",
        f"Total cards: {len(index)}",
        "",
    ]
    # Group official cards by domain.
    for domain in DOMAINS:
        official = [c for c in index if c["domain"] == domain and c["folder"] != PENDING_DIR]
        if not official:
            continue
        lines += [f"## {domain}", ""]
        for c in official:
            year = f" ({c['year']})" if c["year"] else ""
            lines.append(f"- [{c['title']}]({c['path']}) — _{c['type']}_{year}")
        lines.append("")
    pending = [c for c in index if c["folder"] == PENDING_DIR]
    if pending:
        lines += ["## Pending review", ""]
        for c in pending:
            lines.append(f"- [{c['title']}]({c['path']}) — _{c['domain']}_ `{c['status']}`")
        lines.append("")
    (out_dir / "INDEX.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Indexed {len(index)} cards -> index/cards.json, index/INDEX.md")


if __name__ == "__main__":
    main()
